[tool.poetry]
package-mode = false
name = "ex1"
version = "0.0.1"
description = "The best Poetry package of 42's history"
authors = ["god <god@42.fr>", "jesus <jesus@42.fr>"]
license = "1000000 $"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.0"
numpy = "^1.25.0"
matplotlib = "^3.7.2"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
