services:
  my-core-bot-rush:
    image: ghcr.io/42core-team/my-core-bot:rush-00
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
    stdin_open: true

  visualizer:
    image: ghcr.io/42core-team/visualizer:event-01
    environment:
      PORT: 80
      SOCKET_SERVER: "my-core-bot-rush:4242"
      HOST: "127.0.0.1:80"
    ports:
      - 80:80
