NAME = push_swap.a
CC = cc
CFLAGS = -Wextra -Wall -Werror
DFLAGS = -g
C_FILES = push_swap.c

O_FILES = $(C_FILES:.c=.o)
PRINTF_D = ft_printf/
PRINTF_A = libftprintf.a
PRINTF_PATH = $(PRINTF_D)$(PRINTF_A)

all: $(PRINTF_A) $(NAME)